version: "3"

services:
  api-solid-postgresql:
    container_name: api-solid-postgresql
    image: postgres:latest
    ports:
      - 5432:5432 # Primeiro é a porta do host, segundo é a porta do container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=apisolid

  api-solid-postgresql-shadow:
    container_name: api-solid-postgresql-shadow
    image: postgres:latest
    ports:
      - 5433:5432 # Primeiro é a porta do host, segundo é a porta do container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=apisolidShadow
